-- =====================================================================
-- LED Dance 2026 — Supabase Schema (Phase 1)
--
-- Paste this entire file into the Supabase SQL Editor and run.
-- Idempotent: re-running on an existing project will only re-create
-- the helper objects (CREATE OR REPLACE) and skip already-published
-- realtime tables (handled by DO/EXCEPTION blocks).
--
-- Auth model:
--   * Anonymous auth is the primary entry; users provide just a
--     displayName, the frontend calls supabase.auth.signInAnonymously()
--     and then create_program_with_owner / join_program_by_share_code.
--   * The service_role key MUST stay on the server. Phase 2 will only
--     use the anon key in the browser; RLS below is what keeps cloud
--     data isolated per-program.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. Extensions
-- ---------------------------------------------------------------------
create extension if not exists pgcrypto;          -- gen_random_uuid(), random()


-- ---------------------------------------------------------------------
-- 2. Utility functions (created up-front so triggers can reference them)
-- ---------------------------------------------------------------------

-- Bumps `updated_at` on UPDATE for any table that wires this trigger.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- 8-char share code from a confusable-free alphabet (no I/L/O/0/1).
-- Used by create_program_with_owner; collisions are retried in the RPC.
create or replace function public.generate_share_code()
returns text
language plpgsql
volatile
set search_path = public
as $$
declare
  alphabet text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  result   text := '';
  i        int;
begin
  for i in 1..8 loop
    result := result || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
  end loop;
  return result;
end;
$$;

-- Auto-create a profile row whenever Supabase Auth creates a user
-- (anonymous or otherwise). The display_name is later overwritten by the
-- RPCs when the user actually picks one.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'display_name', ''), 'Guest')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;


-- ---------------------------------------------------------------------
-- 3. Tables
-- ---------------------------------------------------------------------

-- profiles ─ extends auth.users with a writable display_name.
create table if not exists public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  display_name  text not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- programs ─ a cloud-shared ProgramArrangement. Identified for invitation
-- by `share_code` (unique, generated by the create RPC).
create table if not exists public.programs (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  share_code      text not null unique,
  schema_version  int  not null default 1,
  created_by      uuid references auth.users(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- program_members ─ M:N program ↔ user with role.
-- Roles: owner (full control), editor (can write), viewer (read only).
--
-- The user_id column carries TWO foreign keys: one to auth.users (the real
-- identity) and one to profiles (so PostgREST can embed display_name via
-- `select=...,profiles!inner(display_name)` — without this second FK the
-- embed fails with "Could not find a relationship between 'program_members'
-- and 'profiles'"). The FK to profiles is safe because handle_new_user()
-- inserts the profile row in the same auth.users-insert trigger.
create table if not exists public.program_members (
  program_id   uuid not null references public.programs(id) on delete cascade,
  user_id      uuid not null references auth.users(id)      on delete cascade,
  role         text not null check (role in ('owner','editor','viewer')),
  joined_at    timestamptz not null default now(),
  primary key (program_id, user_id)
);

-- Add the second FK separately so re-runs against an existing DB still
-- attach the constraint to the already-created table.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'program_members_user_id_profiles_fkey'
  ) then
    alter table public.program_members
      add constraint program_members_user_id_profiles_fkey
      foreign key (user_id) references public.profiles(id) on delete cascade;
  end if;
end;
$$;

-- dances ─ one DanceProject as JSON. `name` is denormalised from
-- dance_json.name for fast listings; clients should keep it in sync.
create table if not exists public.dances (
  id          uuid primary key default gen_random_uuid(),
  program_id  uuid not null references public.programs(id) on delete cascade,
  name        text,
  dance_json  jsonb not null,
  updated_by  uuid references auth.users(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- program_items ─ ordered slots in the arrangement; each picks one dance
-- and the MQTT command that triggers it.
create table if not exists public.program_items (
  id            uuid primary key default gen_random_uuid(),
  program_id    uuid not null references public.programs(id) on delete cascade,
  dance_id      uuid not null references public.dances(id)   on delete cascade,
  order_index   int  not null,
  mqtt_command  text not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- custom_animations ─ one CustomAnimation entry per row.
create table if not exists public.custom_animations (
  id              uuid primary key default gen_random_uuid(),
  program_id      uuid not null references public.programs(id) on delete cascade,
  animation_json  jsonb not null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- export_settings ─ at most one ExportSettings per program (PK = program_id).
create table if not exists public.export_settings (
  program_id    uuid primary key references public.programs(id) on delete cascade,
  settings_json jsonb not null,
  updated_by    uuid references auth.users(id) on delete set null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- activity_log ─ append-only audit / coordination feed. Members can write
-- their own actions and read everyone's.
create table if not exists public.activity_log (
  id          uuid primary key default gen_random_uuid(),
  program_id  uuid not null references public.programs(id) on delete cascade,
  user_id     uuid references auth.users(id) on delete set null,
  action_type text not null,
  details     jsonb,
  created_at  timestamptz not null default now()
);


-- ---------------------------------------------------------------------
-- 4. Indexes
-- ---------------------------------------------------------------------
-- programs.share_code already has a UNIQUE index from the constraint above.
create index if not exists idx_program_members_program_id  on public.program_members  (program_id);
create index if not exists idx_program_members_user_id     on public.program_members  (user_id);
create index if not exists idx_dances_program_id           on public.dances           (program_id);
create index if not exists idx_program_items_program_id    on public.program_items    (program_id, order_index);
create index if not exists idx_custom_animations_program_id on public.custom_animations (program_id);
create index if not exists idx_activity_log_program_recent on public.activity_log     (program_id, created_at desc);


-- ---------------------------------------------------------------------
-- 5. Triggers
-- ---------------------------------------------------------------------

-- updated_at maintenance
drop trigger if exists trg_set_updated_at_profiles          on public.profiles;
drop trigger if exists trg_set_updated_at_programs          on public.programs;
drop trigger if exists trg_set_updated_at_dances            on public.dances;
drop trigger if exists trg_set_updated_at_program_items     on public.program_items;
drop trigger if exists trg_set_updated_at_custom_animations on public.custom_animations;
drop trigger if exists trg_set_updated_at_export_settings   on public.export_settings;

create trigger trg_set_updated_at_profiles
  before update on public.profiles
  for each row execute function public.set_updated_at();

create trigger trg_set_updated_at_programs
  before update on public.programs
  for each row execute function public.set_updated_at();

create trigger trg_set_updated_at_dances
  before update on public.dances
  for each row execute function public.set_updated_at();

create trigger trg_set_updated_at_program_items
  before update on public.program_items
  for each row execute function public.set_updated_at();

create trigger trg_set_updated_at_custom_animations
  before update on public.custom_animations
  for each row execute function public.set_updated_at();

create trigger trg_set_updated_at_export_settings
  before update on public.export_settings
  for each row execute function public.set_updated_at();

-- Auto-profile on auth.users insert.
drop trigger if exists trg_handle_new_user on auth.users;
create trigger trg_handle_new_user
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- ---------------------------------------------------------------------
-- 6. RLS helper functions
-- ---------------------------------------------------------------------
-- These wrap the program_members lookup with SECURITY DEFINER so RLS
-- policies that reference program_members do NOT recursively re-invoke
-- their own RLS check (which would deadlock the policy evaluation).

create or replace function public.is_program_member(_program_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.program_members
    where program_id = _program_id
      and user_id    = auth.uid()
  );
$$;

create or replace function public.get_program_role(_program_id uuid)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.program_members
  where program_id = _program_id
    and user_id    = auth.uid()
  limit 1;
$$;

create or replace function public.can_edit_program(_program_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.program_members
    where program_id = _program_id
      and user_id    = auth.uid()
      and role in ('owner', 'editor')
  );
$$;


-- ---------------------------------------------------------------------
-- 7. Enable RLS on every table that holds program data
-- ---------------------------------------------------------------------
alter table public.profiles          enable row level security;
alter table public.programs          enable row level security;
alter table public.program_members   enable row level security;
alter table public.dances            enable row level security;
alter table public.program_items     enable row level security;
alter table public.custom_animations enable row level security;
alter table public.export_settings   enable row level security;
alter table public.activity_log      enable row level security;


-- ---------------------------------------------------------------------
-- 8. RLS policies
--    Convention: drop existing same-name policy first so this script is
--    re-runnable.
-- ---------------------------------------------------------------------

-- ----- profiles -----
drop policy if exists "profiles: any authed user can read"          on public.profiles;
drop policy if exists "profiles: owner can insert own"              on public.profiles;
drop policy if exists "profiles: owner can update own"              on public.profiles;

create policy "profiles: any authed user can read"
  on public.profiles for select
  to authenticated
  using (true);

create policy "profiles: owner can insert own"
  on public.profiles for insert
  to authenticated
  with check (id = auth.uid());

create policy "profiles: owner can update own"
  on public.profiles for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());


-- ----- programs -----
drop policy if exists "programs: members read"          on public.programs;
drop policy if exists "programs: editors update"        on public.programs;
drop policy if exists "programs: owner deletes"         on public.programs;

create policy "programs: members read"
  on public.programs for select
  to authenticated
  using (public.is_program_member(id));

create policy "programs: editors update"
  on public.programs for update
  to authenticated
  using (public.can_edit_program(id))
  with check (public.can_edit_program(id));

create policy "programs: owner deletes"
  on public.programs for delete
  to authenticated
  using (public.get_program_role(id) = 'owner');

-- (No INSERT policy — programs are created exclusively via the
-- `create_program_with_owner` RPC, which is SECURITY DEFINER and bypasses
-- RLS. Direct INSERTs from the anon key are therefore impossible.)


-- ----- program_members -----
drop policy if exists "program_members: members read fellow members" on public.program_members;
drop policy if exists "program_members: owner manages members"       on public.program_members;
drop policy if exists "program_members: user can leave"              on public.program_members;

create policy "program_members: members read fellow members"
  on public.program_members for select
  to authenticated
  using (public.is_program_member(program_id));

create policy "program_members: owner manages members"
  on public.program_members for all
  to authenticated
  using (public.get_program_role(program_id) = 'owner')
  with check (public.get_program_role(program_id) = 'owner');

create policy "program_members: user can leave"
  on public.program_members for delete
  to authenticated
  using (user_id = auth.uid());

-- (Joining via share code is handled by `join_program_by_share_code`
-- RPC — SECURITY DEFINER, bypasses RLS. Self-INSERT is therefore not
-- exposed to the anon key.)


-- ----- dances -----
drop policy if exists "dances: members read"   on public.dances;
drop policy if exists "dances: editors write"  on public.dances;

create policy "dances: members read"
  on public.dances for select
  to authenticated
  using (public.is_program_member(program_id));

create policy "dances: editors write"
  on public.dances for all
  to authenticated
  using (public.can_edit_program(program_id))
  with check (public.can_edit_program(program_id));


-- ----- program_items -----
drop policy if exists "program_items: members read"  on public.program_items;
drop policy if exists "program_items: editors write" on public.program_items;

create policy "program_items: members read"
  on public.program_items for select
  to authenticated
  using (public.is_program_member(program_id));

create policy "program_items: editors write"
  on public.program_items for all
  to authenticated
  using (public.can_edit_program(program_id))
  with check (public.can_edit_program(program_id));


-- ----- custom_animations -----
drop policy if exists "custom_animations: members read"  on public.custom_animations;
drop policy if exists "custom_animations: editors write" on public.custom_animations;

create policy "custom_animations: members read"
  on public.custom_animations for select
  to authenticated
  using (public.is_program_member(program_id));

create policy "custom_animations: editors write"
  on public.custom_animations for all
  to authenticated
  using (public.can_edit_program(program_id))
  with check (public.can_edit_program(program_id));


-- ----- export_settings -----
drop policy if exists "export_settings: members read"  on public.export_settings;
drop policy if exists "export_settings: editors write" on public.export_settings;

create policy "export_settings: members read"
  on public.export_settings for select
  to authenticated
  using (public.is_program_member(program_id));

create policy "export_settings: editors write"
  on public.export_settings for all
  to authenticated
  using (public.can_edit_program(program_id))
  with check (public.can_edit_program(program_id));


-- ----- activity_log -----
drop policy if exists "activity_log: members read"      on public.activity_log;
drop policy if exists "activity_log: members log self"  on public.activity_log;

create policy "activity_log: members read"
  on public.activity_log for select
  to authenticated
  using (public.is_program_member(program_id));

create policy "activity_log: members log self"
  on public.activity_log for insert
  to authenticated
  with check (
        user_id = auth.uid()
    and public.is_program_member(program_id)
  );

-- (No UPDATE / DELETE policy on activity_log → it's effectively
-- append-only from the anon key. Cleanup is a server-side concern.)


-- ---------------------------------------------------------------------
-- 9. RPC functions
--    Both are SECURITY DEFINER so they can write to programs /
--    program_members / profiles even though the calling client only
--    has the anon role and would otherwise be blocked by RLS.
-- ---------------------------------------------------------------------

-- Creates a program, picks a unique share code (retries on collision),
-- and adds the caller as the owner. Returns the program id + share code
-- so the frontend can immediately route the user into the program.
create or replace function public.create_program_with_owner(
  program_name text,
  display_name text
)
returns table (program_id uuid, share_code text)
language plpgsql
security definer
set search_path = public
as $$
declare
  _user_id     uuid;
  _program_id  uuid;
  _share_code  text;
  _attempt     int := 0;
begin
  _user_id := auth.uid();
  if _user_id is null then
    raise exception 'Not authenticated';
  end if;
  if coalesce(trim(program_name), '') = '' then
    raise exception 'program_name is required';
  end if;

  -- Make sure the profile exists / is up to date.
  insert into public.profiles (id, display_name)
  values (_user_id, coalesce(nullif(trim(display_name), ''), 'Guest'))
  on conflict (id) do update set display_name = excluded.display_name;

  -- Generate a unique share code. Bound the retry loop so a degenerate
  -- collision storm can't hang the request.
  loop
    _attempt   := _attempt + 1;
    _share_code := public.generate_share_code();
    begin
      insert into public.programs (name, share_code, created_by)
      values (program_name, _share_code, _user_id)
      returning id into _program_id;
      exit;
    exception when unique_violation then
      if _attempt >= 8 then
        raise exception 'Could not allocate a unique share code after % attempts', _attempt;
      end if;
    end;
  end loop;

  insert into public.program_members (program_id, user_id, role)
  values (_program_id, _user_id, 'owner');

  insert into public.activity_log (program_id, user_id, action_type, details)
  values (
    _program_id,
    _user_id,
    'program_created',
    jsonb_build_object('name', program_name)
  );

  return query select _program_id, _share_code;
end;
$$;


-- Joins the caller into the program identified by share_code as an
-- editor (or no-ops with the current role if they're already a member).
-- Returns the program id and effective role so the frontend can route.
create or replace function public.join_program_by_share_code(
  input_share_code text,
  display_name     text
)
returns table (program_id uuid, role text)
language plpgsql
security definer
set search_path = public
as $$
declare
  _user_id        uuid;
  _program_id     uuid;
  _existing_role  text;
begin
  _user_id := auth.uid();
  if _user_id is null then
    raise exception 'Not authenticated';
  end if;
  if coalesce(trim(input_share_code), '') = '' then
    raise exception 'share_code is required';
  end if;

  -- Refresh / create the profile.
  insert into public.profiles (id, display_name)
  values (_user_id, coalesce(nullif(trim(display_name), ''), 'Guest'))
  on conflict (id) do update set display_name = excluded.display_name;

  -- Resolve the share code (case sensitive — generate_share_code
  -- always produces uppercase, so the frontend should upper() user input
  -- before calling, OR we could `upper()` here — keeping strict for now).
  select p.id into _program_id
  from public.programs p
  where p.share_code = input_share_code;

  if _program_id is null then
    raise exception 'Invalid share code';
  end if;

  select pm.role into _existing_role
  from public.program_members pm
  where pm.program_id = _program_id
    and pm.user_id    = _user_id;

  if _existing_role is null then
    insert into public.program_members (program_id, user_id, role)
    values (_program_id, _user_id, 'editor');
    _existing_role := 'editor';

    insert into public.activity_log (program_id, user_id, action_type, details)
    values (
      _program_id,
      _user_id,
      'member_joined',
      jsonb_build_object('display_name', display_name)
    );
  end if;

  return query select _program_id, _existing_role;
end;
$$;

-- Allow anon-signed-in clients to call the RPCs.
grant execute on function public.create_program_with_owner(text, text) to authenticated;
grant execute on function public.join_program_by_share_code(text, text) to authenticated;


-- ---------------------------------------------------------------------
-- 10. Realtime publication
--     Add tables to `supabase_realtime`. Wrapped in DO blocks so the
--     script is re-runnable — adding an already-published table raises
--     `duplicate_object`, which we silently swallow.
-- ---------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'programs',
    'program_members',
    'dances',
    'program_items',
    'custom_animations',
    'export_settings',
    'activity_log'
  ] loop
    begin
      execute format('alter publication supabase_realtime add table public.%I', t);
    exception when duplicate_object then
      -- already published; nothing to do
      null;
    when undefined_object then
      -- supabase_realtime publication doesn't exist yet (rare on a fresh
      -- self-hosted install). Surface the error clearly.
      raise exception 'Publication "supabase_realtime" not found. Create it first or enable Realtime in the Supabase dashboard.';
    end;
  end loop;
end;
$$;


-- ---------------------------------------------------------------------
-- 11. Replica identity FULL
--     With the default REPLICA IDENTITY, DELETE events expose only the
--     primary key. Realtime subscribers filtering by `program_id` would
--     then miss deletes (program_id is no longer in the WAL row). FULL
--     ships every column on UPDATE and DELETE so client-side
--     `program_id=eq.<X>` filters work for every event type.
--
--     Trade-off: WAL volume is higher, especially for `dances` whose
--     `dance_json` may be large.
-- ---------------------------------------------------------------------
alter table public.dances            replica identity full;
alter table public.program_items     replica identity full;
alter table public.custom_animations replica identity full;
alter table public.export_settings   replica identity full;
alter table public.program_members   replica identity full;
alter table public.activity_log      replica identity full;
-- programs is keyed by id and clients subscribe per-id, so DEFAULT is fine.


-- ---------------------------------------------------------------------
-- 12. Sanity grants
--     The anon role itself never needs direct table access — clients
--     authenticate first and get the `authenticated` role. Granting
--     usage on the schema is enough for RLS-controlled access.
-- ---------------------------------------------------------------------
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
-- New tables created later by this script will need:
--   alter default privileges in schema public grant ... to authenticated;
-- but we already granted on `all tables` above for the existing set.

-- =====================================================================
-- End of schema.
-- =====================================================================
